version: "3"
services:
  postgres:
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres

  zabbix-server:
    image: zabbix/zabbix-server-pgsql
    environment:
      DB_SERVER_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  zabbix-agent:
    image: zabbix/zabbix-agent
    environment:
      ZBX_SERVER_HOST: zabbix-server
      ZBX_HOSTNAME: zabbix-server
    links:
      - zabbix-server

  zabbix-client:
    image: zabbix/zabbix-web-nginx-pgsql
    environment:
      PHP_TZ: "America/Sao_Paulo"
      ZBX_SERVER_HOST: zabbix-server
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      DB_SERVER_HOST: postgres
    links:
      - zabbix-server
      - postgres
    ports:
      - 8080:8080
