version: "3"
services:
  postgres:
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres

  zabbix-server:
    container_name: zabbix-server
    image: zabbix/zabbix-server-pgsql:alpine-latest
    environment:
      DB_SERVER_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  zabbix-client:
    container_name: zabbix-client
    image: zabbix/zabbix-web-nginx-pgsql:alpine-latest
    environment:
      PHP_TZ: "America/Sao_Paulo"
      ZBX_SERVER_HOST: zabbix-server
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      DB_SERVER_HOST: postgres
    links:
      - zabbix-server
      - postgres
    ports:
      - 8080:8080

  linux01:
    container_name: linux01
    image: zabbix/zabbix-agent:alpine-latest
    environment:
      ZBX_SERVER_HOST: zabbix-server
      ZBX_HOSTNAME: linux01
    depends_on:
      - zabbix-server

  linux02:
    container_name: linux02
    image: zabbix/zabbix-agent:alpine-latest
    environment:
      ZBX_SERVER_HOST: zabbix-server
      ZBX_HOSTNAME: linux02
    depends_on:
      - zabbix-server

  linux03-snmp:
    container_name: linux03-snmp
    image: tandrup/snmpsim
